### ISSUE TITLE
can not run the project locally 

### ISSUE THREAD

**Issue by am0029** [eknoorpreet/dev.to-clone#4]
i asked question here with 

https://stackoverflow.com/questions/74739404/uncaught-in-promise-typeerror-failed-to-fetch-i-can-not-connect-to-api-from
no connection to the backend

**Comment by am0029** [comment]
the create post is also not working ? am i wrong ? or i do something wrong ?

**Comment by eknoorpreet** [comment]
Hi @am0029, thanks for the issue. The error in question is related to CORS.

Quoting [this answer](https://stackoverflow.com/a/46988108):

> This error occurs when the client URL and server URL don't match, including the port number. In this case you need to enable your service for CORS which is cross-origin resource sharing.

This means that the server (5000) and client (3000) cannot share resources as they are on different ports, which is why we need to enable CORS. Initially, I had allowed resource-sharing between any client but seems like it's resulting in errors locally.

Now, I've changed it to whatever `CLIENT_URL` you use, i.e.the one that you pass in `.env` file and on which the client runs. Ex: http://localhost:3000. If you're using live-server, pass that as `CLIENT_URL: http://127.0.0.1:3000`

Hope this helps!

**Comment by am0029** [comment]
I delete the source code after  1 month messing with . when i saw too many errors . and one of them even can not create a simple post . 

it simply site has just 1 function : create post . and that 1 function is not working !! after 1 month messing with source code i could not understand why i am not able to post . 

it means when some one sighn up in site he can not create post . because of type fetch error . can u look ? because no one will correct someone else source code in stack over flow . 1 month zero answer

**Comment by am0029** [comment]
the cors error is still there and fetch error . can u test ?

after u change client_url i test but still same error

just test if u can register to the website or not . it is impossible to register with this cors error 

and cors error is also for socket io . can u check that also

**Comment by am0029** [comment]
see can not post https://postimg.cc/5X46fQVg
submit button is always off 

can u see this problems . i do not know . i know this source is for practice but this too many problems .  do u really not see this problems ?

**Comment by am0029** [comment]
please see what is problem is 
https://stackoverflow.com/questions/74753176/each-child-in-a-list-should-have-a-unique-key-prop-check-the-render-method-o

**Comment by eknoorpreet** [comment]
Did you clone the latest copy (or pull the latest changes) and then tested?

> just test if u can register to the website or not . it is impossible to register with this cors error

What usually happens is that over time, things change. Packages get outdated and since I work full-time, I may not be able to monitor the changes regularly. For example, the live version does not work because the backend is hosted on Heroku, which no longer has a free tier. It's paid now so I may or may not upgrade to the paid version to host live. But I just tried it locally and it works as expected.

The fetch error is basically the CORS error. As I said, I've tested and pushed a fix.

> submit button is always off

That's a feature. You should not be able to create a post if you don't fill in all the required fields.

Regarding the errors on unique keys, I'm aware of the problem but haven't had the time to fix it. It doesn't affect creating posts or anything else.

Here's a [recording](https://streamable.com/q7buhu) of it working.

**Comment by am0029** [comment]
Hello thanks for answering me problem is i start the project locally right ?

npm start in backend and client they both working and fill 2 .env file 

but i connected to backend and i fix the key issue based on answer on stack over flow 
https://stackoverflow.com/questions/74753176/each-child-in-a-list-should-have-a-unique-key-prop-check-the-render-method-o

but the problem is 
1- .user can not sign up if he wants upload image  because after i spend too much time to talk with cloudinary support and adding api key and secret to project and .... but not working . user just can sign up if he does not wants upload image

2- the second problem is users avatar not showing because of cloudinary problem because nothing will be uploaded to cloudinay

3 the most important section is submit button is disabled all the time no matter what inputs are . fill or not fill
submit button is disabled and no user can create post . no matter with information in input or without information 
and of course image no uploaded to cloudinary 


i choose this project for my  college but too many error that i can not fix at all . i come here and ask from developer fix this issues . 

I spend 1 month fixing this 3  problems but i could not . I have to pay to a developer to fix some one else code for a college project .    if u had time please fix this 3 issues .  i am stocked into your code . i have to pay for developer to fix this issues if u not going to fix this issues .
.
